version: '3.2'

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:6379
    node1:
        image: jilsx/nodedemo
        depends_on: ["redis"]
        build: .
        container_name: nodedemo
        ports:
            - 8081:8081
        restart: always
